function y = untitled(x)
%UNTITLED Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 28-Apr-2015 19:14:51

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.09;  % Stopband Frequency
    Fpass = 0.1;   % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 1;     % Passband Ripple (dB)
    Fs    = 2;     % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


